/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef LATX_TEST_X11_ASYNC_BRIDGE_VALUES_H
#define LATX_TEST_X11_ASYNC_BRIDGE_VALUES_H

#define ASYNC_PROBE_EVENTS_RETURN 0x5151
#define ASYNC_PROBE_FLUSH_RETURN 0x5252
#define ASYNC_PROBE_REPLY_LENGTH 32

#endif
