#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Authenticate the final LAT CI callback before publishing a Check Run."""

import argparse
import hashlib
import hmac
import json
import os
import re
import time


SHA_PATTERN = re.compile(r"[0-9a-f]{40,64}", re.IGNORECASE)
SIGNATURE_PATTERN = re.compile(r"sha256=[0-9a-f]{64}")
MAX_CALLBACK_AGE_SECONDS = 15 * 60
MAX_FUTURE_SKEW_SECONDS = 60


class LatCICallbackError(ValueError):
    """The callback cannot prove it was generated by the LAT CI hub."""


def _canonical_payload(repository, head_sha, conclusion, summary, details_url, timestamp):
    return json.dumps(
        {
            "callback_repository": repository,
            "conclusion": conclusion,
            "details_url": details_url,
            "head_sha": head_sha,
            "summary": summary,
            "timestamp": timestamp,
        },
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def create_signature(secret, repository, head_sha, conclusion, summary, details_url, timestamp):
    """Return the protocol signature that the Hub adds to callback inputs."""
    if not isinstance(secret, str) or not secret:
        raise LatCICallbackError("LAT_CI_CHECK_CALLBACK_SECRET is required")
    payload = _canonical_payload(
        repository, head_sha, conclusion, summary, details_url, timestamp
    )
    return "sha256=" + hmac.new(
        secret.encode("utf-8"), payload, hashlib.sha256
    ).hexdigest()


def verify_callback(secret, repository, head_sha, conclusion, summary, details_url,
                    timestamp_value, signature, now=None):
    """Reject unsigned, stale, altered, or malformed callback inputs."""
    if not isinstance(repository, str) or not repository.strip():
        raise LatCICallbackError("callback repository is invalid")
    if not isinstance(head_sha, str) or not SHA_PATTERN.fullmatch(head_sha):
        raise LatCICallbackError("head_sha must be a Git commit SHA")
    if conclusion not in {"success", "failure"}:
        raise LatCICallbackError("conclusion is invalid")
    if not isinstance(summary, str) or not summary.strip():
        raise LatCICallbackError("summary is invalid")
    if not isinstance(details_url, str) or not details_url.startswith("https://"):
        raise LatCICallbackError("details_url is invalid")
    if not isinstance(timestamp_value, str) or not re.fullmatch(r"[1-9][0-9]*", timestamp_value):
        raise LatCICallbackError("callback_timestamp is invalid")
    timestamp = int(timestamp_value)
    current_time = int(time.time() if now is None else now)
    if timestamp > current_time + MAX_FUTURE_SKEW_SECONDS:
        raise LatCICallbackError("callback timestamp is in the future")
    if current_time - timestamp > MAX_CALLBACK_AGE_SECONDS:
        raise LatCICallbackError("callback signature has expired")
    if not isinstance(signature, str) or not SIGNATURE_PATTERN.fullmatch(signature):
        raise LatCICallbackError("callback_signature is invalid")

    expected = create_signature(
        secret, repository, head_sha, conclusion, summary, details_url, timestamp
    )
    if not hmac.compare_digest(signature, expected):
        raise LatCICallbackError("callback signature does not match")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository", required=True)
    parser.add_argument("--head-sha", required=True)
    parser.add_argument("--conclusion", required=True)
    parser.add_argument("--summary", required=True)
    parser.add_argument("--details-url", required=True)
    parser.add_argument("--timestamp", required=True)
    parser.add_argument("--signature", required=True)
    args = parser.parse_args()

    try:
        verify_callback(
            os.environ.get("LAT_CI_CHECK_CALLBACK_SECRET", ""),
            args.repository,
            args.head_sha,
            args.conclusion,
            args.summary,
            args.details_url,
            args.timestamp,
            args.signature,
        )
    except LatCICallbackError as error:
        raise SystemExit(f"LAT CI callback rejected: {error}") from error


if __name__ == "__main__":
    main()
