#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Generate the audited SHBR opcode semantic table."""

import argparse
import json
import sys
from pathlib import Path


RULES = {
    "SRC1",
    "ACCESS",
    "ACCESS_READ",
    "DEST",
    "READ_ACCESS",
    "OTHER",
    "ZERO",
    "IGNORE",
    "MOVSS",
    "MOVSD",
    "MOVD",
    "MOVQ",
    "BROADCAST",
    "EXTRACT",
    "EXTRACT128",
    "BYTE_SHIFT",
    "SCALAR_SHIFT",
    "GATHER",
    "MASKMOV",
    "PCMPSTR",
    "PSIGN",
    "IMPLICIT",
}


class GenerationError(Exception):
    pass


def inventory_mnemonics(data):
    names = []
    for group in data["unmodeled_groups"]:
        names.extend(group["mnemonics"])
    if len(names) != len(set(names)):
        raise GenerationError("duplicate inventory mnemonic")
    return set(names)


def exact_rules(data):
    inventory = inventory_mnemonics(data)
    groups = {
        mnemonic: group["name"]
        for group in data["unmodeled_groups"]
        for mnemonic in group["mnemonics"]
    }
    already_promoted = set(data["promoted_opcode_specific"])
    generated = inventory - already_promoted
    default = data["exact_rule_default"]
    overrides = data.get("exact_rule_overrides", {})

    unknown = set(overrides) - generated
    if unknown:
        raise GenerationError(
            "exact rule overrides are not newly promoted entries: "
            f"{sorted(unknown)}"
        )
    result = {}
    for mnemonic in sorted(generated):
        semantic = dict(default)
        if groups[mnemonic] == "fma_unmodeled":
            if mnemonic.endswith("SS"):
                semantic = {"high32": "DEST", "high64": "DEST"}
            elif mnemonic.endswith("SD"):
                semantic["high32"] = "ACCESS_READ"
                semantic["high64"] = "DEST"
            else:
                semantic = {
                    "high32": "ACCESS_READ",
                    "high64": "ACCESS_READ",
                }
        elif groups[mnemonic] == "vcmp_unmodeled":
            if mnemonic.endswith("SS"):
                semantic = {"high32": "SRC1", "high64": "SRC1"}
            elif mnemonic.endswith("SD"):
                semantic["high32"] = "ACCESS_READ"
                semantic["high64"] = "SRC1"
            else:
                semantic = {
                    "high32": "ACCESS_READ",
                    "high64": "ACCESS_READ",
                }
        elif (mnemonic.startswith("CMP") and
              (mnemonic.endswith("PS") or mnemonic.endswith("PD"))):
            semantic = {
                "high32": "ACCESS_READ",
                "high64": "ACCESS_READ",
            }
        semantic.update(overrides.get(mnemonic, {}))
        for region in ("high32", "high64"):
            rule = semantic.get(region)
            if rule not in RULES:
                raise GenerationError(
                    f"{mnemonic} has invalid {region} rule: {rule}"
                )
        result[mnemonic] = semantic
    return result


def render(data):
    lines = [
        "/* SPDX-License-Identifier: GPL-2.0-only */",
        "/* Generated by scripts/generate_latx_hbr_semantics.py. */",
    ]
    for mnemonic, semantic in exact_rules(data).items():
        lines.append(
            f"    [WRAP({mnemonic})] = {{ SHBR_RULE_{semantic['high32']}, "
            f"SHBR_RULE_{semantic['high64']} }},"
        )
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser()
    root = Path(__file__).resolve().parents[1]
    parser.add_argument(
        "--inventory",
        type=Path,
        default=root / "target/i386/latx/optimization/hbr-xmm-semantics.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=root / "target/i386/latx/optimization/hbr-xmm-semantics.inc",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    try:
        data = json.loads(args.inventory.read_text(encoding="utf-8"))
        expected = render(data)
        if args.check:
            actual = args.output.read_text(encoding="utf-8")
            if actual != expected:
                raise GenerationError(
                    f"generated table is stale: {args.output}"
                )
        else:
            args.output.write_text(expected, encoding="utf-8")
    except (OSError, json.JSONDecodeError, GenerationError) as exc:
        print(f"SHBR semantic generation failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
